### ISSUE TITLE
Got error when running sbt

### ISSUE THREAD

**Issue by phuna** [bplawler/crawler#7]
Hi,
I just cd into the source and run `sbt` command then I got this error. Could you help?
```
[info] Loading project definition from /Users/myuser/crawler/project
[debug]
[debug] Initial source changes:
[debug]         removed:Set()
[debug]         added: Set()
[debug]         modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug]
[debug] Sources indirectly invalidated by:
[debug]         product: Set()
[debug]         binary dep: Set()
[debug]         external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings:
[debug]
[debug] [Loading] Scanning directory /Users/myuser/crawler
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/myuser/crawler, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(com.typesafe.sbt.GitVersioning), Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(bintray.BintrayPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(com.typesafe.sbt.GitBranchPrompt),Set(Atom(com.typesafe.sbt.GitPlugin))), Clause(Atom(com.typesafe.sbt.GitVersioning),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(com.typesafe.sbt.GitVersioning),Set(Atom(com.typesafe.sbt.GitPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(bintray.BintrayPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(com.typesafe.sbt.GitPlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,com.typesafe.sbt.GitVersioning,com.typesafe.sbt.GitPlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,bintray.BintrayPlugin,sbt.plugins.JUnitXmlReportPlugin)
[debug] sorting: ns: List(sbt.plugins.CorePlugin, com.typesafe.sbt.GitVersioning, com.typesafe.sbt.GitPlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, bintray.BintrayPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin) not found List(com.typesafe.sbt.GitVersioning, com.typesafe.sbt.GitPlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, bintray.BintrayPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, com.typesafe.sbt.GitPlugin, sbt.plugins.IvyPlugin) not found List(com.typesafe.sbt.GitVersioning, sbt.plugins.JvmPlugin, bintray.BintrayPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, com.typesafe.sbt.GitPlugin, sbt.plugins.IvyPlugin, com.typesafe.sbt.GitVersioning, sbt.plugins.JvmPlugin) not found List(bintray.BintrayPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug]   :: sorting:: found: List(sbt.plugins.CorePlugin, com.typesafe.sbt.GitPlugin, sbt.plugins.IvyPlugin, com.typesafe.sbt.GitVersioning, sbt.plugins.JvmPlugin, bintray.BintrayPlugin, sbt.plugins.JUnitXmlReportPlugin) not found List()
[debug]   :: sorted deduced result: List(sbt.plugins.CorePlugin, com.typesafe.sbt.GitPlugin, sbt.plugins.IvyPlugin, com.typesafe.sbt.GitVersioning, sbt.plugins.JvmPlugin, bintray.BintrayPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug] [Loading] Done in /Users/myuser/crawler, returning: (crawler)
java.lang.RuntimeException: Setting value cannot be null: {file:/Users/myuser/crawler/}/*:version
        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/Users/myuser/crawler/}/*:version
```

**Comment by bplawler** [comment]
It would appear that there is no version set.  Can you try adding a 

version := "0.1"

To your local build and see if that fixes it.

**Comment by phuna** [comment]
After adding `version := "0.1"` it shows more error about bintray credentials. Is bintray account information required?
```
[info] Loading project definition from /Users/myuser/crawler/project
Missing bintray credentials /Users/myuser/.bintray/.credentials. Some bintray features depend on this.
java.lang.RuntimeException: Setting value cannot be null: {file:/Users/myuser/crawler/}/*:version
        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/Users/myuser/crawler/}/*:version
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
My `build.sbt`, just in case:
```
organization := "io.github"
name := "crawler"
version := "1.0"

crossScalaVersions := Seq("2.11.7", "2.10.5")
scalaVersion := crossScalaVersions.value.head
scalacOptions := Seq("-deprecation", "-unchecked", "-feature")

libraryDependencies ++= Seq (
    "net.sourceforge.htmlunit" % "htmlunit" % "2.15"
  , "org.specs2" %% "specs2-core" % "3.6.2" % "test"
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

enablePlugins(GitVersioning)
git.useGitDescribe := true // figure out version from last tag

// required for release to bintray
licenses += ("Apache-2.0", url("http://www.apache.org/licenses/LICENSE-2.0"))
```

**Comment by 2m** [comment]
Sorry, I sneaked this in. My [PR](https://github.com/bplawler/crawler/pull/6) added [sbt-git](https://github.com/sbt/sbt-git) plugin to the build. This means that the version of the project is now calculated from the git repository using `git describe --tags` command. As I mentioned [here](https://github.com/bplawler/crawler/pull/6#issue-97340384) sbt-git plugin has a [known issue](https://github.com/sbt/sbt-git/issues/89) where it fails to load a project if the code repository have no tags created. It has already been fixed, but we need a new version of sbt-git plugin.

The workaround is to create a tag, for example tagging the first commit of this repository: `git tag 0.1 1d1db8c`.

**Comment by phuna** [comment]
@2m : Thanks! Adding a tag solves the problem :+1:

**Comment by bplawler** [comment]
@phuna @2m Also added a tag to mine so future cloners won't run into this.  Thanks again @2m!
